DoctorOffice.Solution/DoctorOffice/Models/Patient.cs
using System;
using System.Collections.Generic;

namespace DoctorOffice.Models
{
  public class Patient
  {
    public int PatientId { get; set; }
    public string FirstName { get; set; }
    public string LastName { get; set; }
    public DateTime DOB { get; set; }
    public string PhoneNumber { get; set; }
    public string Allergies { get; set; }
    public string MedicalHistory { get; set; }
    public virtual ApplicationUser User { get; set; }
    public ICollection<DoctorPatient> Doctors { get; set; }

    public Patient()
    {
      this.Doctors = new HashSet<DoctorPatient>();
    }

  }
}

DoctorOffice.Solution/DoctorOffice/Controllers/PatientsController.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using System.Threading.Tasks;
using System.Security.Claims;
using DoctorOffice.Models;
using System.Collections.Generic;
using System.Linq;
using System;

namespace DoctorOffice.Controllers
{
  [Authorize]
  public class PatientsController : Controller
  {
    private readonly DoctorOfficeContext _db;
    private readonly UserManager<ApplicationUser> _userManager;

    public PatientsController(UserManager<ApplicationUser> userManager, DoctorOfficeContext db)
    {
      _userManager = userManager;
      _db = db;
    }

    public async Task<ActionResult> Index()
    {
      var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      var currentUser = await _userManager.FindByIdAsync(userId);
      var userPatients = _db.Patients.Where(entry => entry.User.Id == currentUser.Id);
      return View(userPatients);
    }

    public ActionResult Details(int id)
    {
      var thisPatient = _db.Patients
        .Include(patient => patient.Doctors)
        .ThenInclude(join => join.Doctor)
        .FirstOrDefault(patient => patient.PatientId == id);
      return View(thisPatient);
    }

    public ActionResult Create()
    {
      ViewBag.DoctorId = new SelectList(_db.Doctors, "DoctorId", "LastName");
      return View();
    }

    [HttpPost]
    public async Task<ActionResult> Create(Patient patient, int DoctorId)
    {
      try
      {
        var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
        var currentUser = await _userManager.FindByIdAsync(userId);
        patient.User = currentUser;
        _db.Patients.Add(patient);
        if (DoctorId != 0)
        {
          _db.DoctorPatients.Add(new DoctorPatient() { DoctorId = DoctorId, PatientId = patient.PatientId });
        }
        _db.SaveChanges();
      }
      catch (Exception ex)
      {
        Console.WriteLine("Exception Error in Create(): " + ex);
      }
      return RedirectToAction("Index");  
    }

    public ActionResult Edit(int id)
    {
      var thisPatient = _db.Patients.FirstOrDefault(patient => patient.PatientId == id);
      ViewBag.DoctorId = new SelectList(_db.Doctors, "DoctorId", "LastName");
      return View(thisPatient);
    }

    [HttpPost]
    public ActionResult Edit(Patient patient)
    {
      try
      {
        _db.Entry(patient).State = EntityState.Modified;
        _db.SaveChanges();
      }
      catch (Exception ex)
      {
        TempData["ErrorMessage"] = "An Error occurred. Please see the Console for details.";
        Console.WriteLine("Exception Error in Edit(): " + ex);
      }
      return RedirectToAction("Index");
    }

    public async Task<ActionResult> AddDoctor(int id)
    {
      var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      var currentUser = await _userManager.FindByIdAsync(userId);
      var thisPatient = _db.Patients.FirstOrDefault(patients => patients.PatientId == id);
      ViewBag.DoctorId = new SelectList(_db.Doctors.Where(doctors => doctors.AcceptNewPatients == true && doctors.User.Id == currentUser.Id), "DoctorId", "LastName");
      return View(thisPatient);
    }

    [HttpPost]
    public ActionResult AddDoctor(Patient patient, int DoctorId)
    {
      try
      {
        _db.DoctorPatients.Add(new DoctorPatient() { DoctorId = DoctorId, PatientId = patient.PatientId });
        _db.SaveChanges();
      }
      catch (DbUpdateException ex)
      {
        TempData["ErrorMessage"] = "This patient is already seeing the selected doctor.";
        Console.WriteLine("Database Update Exception Error in AddDoctor(): " + ex);
      }
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      var thisPatient = _db.Patients.FirstOrDefault(patients => patients.PatientId == id);
      return View(thisPatient);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      try
      {
        var thisPatient = _db.Patients.FirstOrDefault(patients => patients.PatientId == id);
        _db.Patients.Remove(thisPatient);
        _db.SaveChanges();
      }
      catch (Exception ex)
      {
        TempData["ErrorMessage"] = "An Error occurred. Please see the Console for details.";
        Console.WriteLine("Exception Error in DeleteConfirmed(): " + ex);
      }
      return RedirectToAction("Index");
    }

    [HttpPost]
    public ActionResult DeleteDoctor(int joinId)
    {
      try
      {
        var joinEntry = _db.DoctorPatients.FirstOrDefault(entry => entry.DoctorPatientId == joinId);
        _db.DoctorPatients.Remove(joinEntry);
        _db.SaveChanges();
      }
      catch (Exception ex)
      {
        TempData["ErrorMessage"] = "An Error occurred. Please see the Console for details.";
        Console.WriteLine("Exception Error in DeleteConfirmed(): " + ex);
      }
      return RedirectToAction("Index");
    }

    public ActionResult Search()
    {
      List<Patient> allPatients = _db.Patients.ToList();
      return View();
    }

    [HttpPost]
    public ActionResult Search(Patient searchPatient)
    {
      List<Patient> foundPatients = _db.Patients.ToList();
      try
      {
        if(searchPatient.LastName != null)
        {
          string nameSearch = searchPatient.LastName.ToLower();
          foundPatients = foundPatients.FindAll(patients => patients.LastName.ToLower().Equals(nameSearch) == true);
          // Console.WriteLine("Name Search: " + nameSearch);
          // Console.WriteLine("Found Patients: " + foundPatients);
        }
        if(searchPatient.DOB != null)
        {
          foundPatients = foundPatients.FindAll(patients => patients.DOB.Equals(searchPatient.DOB) == true);
          // Console.WriteLine("DOB Search: " + searchPatient.DOB);
          // Console.WriteLine("Found Patients: " + foundPatients);
        }
      }
      catch (Exception ex)
      {
        TempData["ErrorMessage"] = "An Error occurred. Please see the Console for details.";
        Console.WriteLine("Exception Error in Search(): " + ex);
      }
      return View("SearchResult", foundPatients);
    }

  }
}

DoctorOffice.Solution/DoctorOffice/Views/Patients/AddDoctor.cshtml
@{
  Layout = "_Layout";
  ViewBag.Title = "Assign Doctor to Patient";
}

@model DoctorOffice.Models.Patient

<div class="assignDoctor">
  <h2>Assign a Doctor</h2>

  <h4>Assign a doctor to this patient: @Html.DisplayFor(model => model.LastName), @Html.DisplayFor(model => model.FirstName)</h4>

  @using (Html.BeginForm())
  {
    @Html.HiddenFor(model => model.PatientId)

    @Html.Label("Select doctor")
    @Html.DropDownList("DoctorId")

    <input type="submit" value="Save" class="w3-button w3-indigo"/>
  }

  <p>Note: Some providers are not shown in the list because they are currently not accepting new patients.</p>

</div>

DoctorOffice.Solution/DoctorOffice/Views/Patients/Create.cshtml
@{
  Layout = "_Layout";
  ViewBag.Title = "Create Patient";
}

@model DoctorOffice.Models.Patient

<div class="patientCreate">
  <h1><strong>Add Patient</h1></strong>
  @using (Html.BeginForm())
  {
    @Html.Label("First Name")
    @Html.TextBoxFor(model => model.FirstName, new { @type="text", @placeholder="John",@required = "required", @class="form-control"})

    @Html.Label("Last Name")
    @Html.TextBoxFor(model => model.LastName, new { @type="text", @placeholder="Doe",@required = "required", @class="form-control"})

    @Html.Label("Date of Birth")
    @Html.TextBoxFor(model => model.DOB, new { @type="date", @placeholder="Doe",@required = "required", @class="form-control"})

    @Html.Label("Phone Number")
    @Html.TextBoxFor(model => model.PhoneNumber, new { @type="tel", @placeholder="1234567890", @maxlength="10", @required = "required", @class="form-control"})
    
    @Html.Label("Allergies")
    @Html.TextBoxFor(model => model.Allergies, new { @type="text", @placeholder="Bees",@required = "required", @class="form-control"})
   
    @Html.Label("Medical History")
    @Html.TextBoxFor(model => model.MedicalHistory, new { @type="text", @placeholder="Asthma",@required = "required", @class="form-control"})
    <br>
    <input type="submit" value="Add New Patient" class="w3-button w3-indigo" />
  }

</div>

DoctorOffice.Solution/DoctorOffice/Views/Patients/Delete.cshtml
@{
  Layout = "_Layout";
}

@model DoctorOffice.Models.Patient

<div class="patientDelete">
  <h2>Are you sure you want to remove this Patient?</h2>
  <h1><strong>Delete this paitent?</strong></h1>

  @Html.DisplayFor(model => model.FirstName) @Html.DisplayFor(model => model.LastName)
  @using (Html.BeginForm())
  {
    <br>
    <input type="submit" value="Delete" class="w3-button w3-indigo">
  }

</div>

DoctorOffice.Solution/DoctorOffice/Views/Patients/Details.cshtml
@{
  Layout = "_Layout";
  ViewBag.Title = "Patient Details";
}

@model DoctorOffice.Models.Patient

<div class="patientDetails">
  <h1><strong>Patient Details</h1></strong>
  <p>Name : @Html.DisplayFor(model => model.LastName), @Html.DisplayFor(model => model.FirstName)</p>
  <p>Date of Birth : @Html.DisplayFor(model => model.DOB.Month)/@Html.DisplayFor(model => model.DOB.Day)/@Html.DisplayFor(model => model.DOB.Year)</p>
  <p>Phone Number : @Html.DisplayFor(model => model.PhoneNumber)</p>
  <p>Allergies : @Html.DisplayFor(model => model.Allergies)</p>
  <p>Medical History : @Html.DisplayFor(model => model.MedicalHistory)</p>
 
  @if (@Model.Doctors.Count > 0)
  {
    <p>@Html.DisplayFor(model => model.LastName)'s Treatment Team :</p>
    @foreach(var join in Model.Doctors)
    {
      <p>Dr. @join.Doctor.LastName, @join.Doctor.FirstName | @join.Doctor.Specialty</p>
      @using (Html.BeginForm("DeleteDoctor", "Patients"))
      {
        @Html.Hidden("joinId", @join.DoctorPatientId)
        <input type="submit" value="Delete" class="w3-button w3-indigo"/>
      }
    }
  }
    <hr>
    <p>@Html.ActionLink("Assign a Doctor To This Patient", "AddDoctor", new { id = Model.PatientId })</p>
    <hr>
     <div id="patientDetailsLinks">
    <p><img src="~/img/eraser.png" style="width: 30px;">@Html.ActionLink("Edit This Patient's Information", "Edit", new { id = Model.PatientId})</p>
    <p><img src="~/img/delete.png" style="width: 30px;">@Html.ActionLink("Delete This Patient", "Delete", new { id = Model.PatientId})</p>
  </div>
</div>

DoctorOffice.Solution/DoctorOffice/Views/Patients/Edit.cshtml
@{
  Layout ="_Layout";
  ViewBag.Title ="Update Patient";
}

@model DoctorOffice.Models.Patient;

<div class="patientEdit">
<h1><strong>Update</strong></h1>

<h4>Update Patient Information : @Html.DisplayFor(model => model.LastName)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.PatientId)

  <br>
  @Html.Label("First Name")
  @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @type="text", @class="form-control" } })

  @Html.Label("Last Name")
  @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @type="text", @class="form-control" } })

  @Html.Label("Date of Birth")
  @Html.TextBoxFor(model => model.DOB, "{0:MM-dd-yyyy}")

  <br>
  @Html.Label("Phone Number")
  @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @type="text", @class="form-control" } })

  @Html.Label("Allergies")
  @Html.EditorFor(model => model.Allergies, new { htmlAttributes = new { @type="text", @class="form-control" } })

  @Html.Label("Medical History")
  @Html.EditorFor(model => model.MedicalHistory, new { htmlAttributes = new { @type="text", @class="form-control" } })
  <br>
  <input type="submit" value="Save" class="w3-button w3-indigo" />
}


</div>

DoctorOffice.Solution/DoctorOffice/Views/Patients/Index.cshtml
@{
  Layout = "_Layout";
  ViewBag.Title = "All Patients";
}

@using DoctorOffice.Models;
@model IEnumerable<DoctorOffice.Models.Patient>;

<div class="patientsIndex">

  
  <h1><strong>List of Patients</strong></h1>
  @if (Model.Any())
  {
    @foreach (Patient patient in Model)
   {
      <h3>@Html.ActionLink($"{patient.FirstName} {patient.LastName}", "Details", new { id = patient.PatientId })</h3>
    }
  }
  else
  {
    <p>There are currently no patients registered. Click below to add a new patient.</p>
  }
<div class="exceptionError">
    @if (TempData.ContainsKey("ErrorMessage"))
    {
    <h4>@TempData["ErrorMessage"]</h4>
    }
</div>

  <div id="patientIndexLinks">
    <p><img src="~/img/add-friend.png" style="width: 30px;">@Html.ActionLink("Add a new patient", "Create")</p>
    <p><img src="~/img/barcode.png" style="width: 30px;">@Html.ActionLink("Search for Patients", "Search")</p>
  </div>
</div>

DoctorOffice.Solution/DoctorOffice/Views/Patients/Search.cshtml
@{
  Layout = "_Layout";
  ViewBag.Title = "Search Patients";
}

@using DoctorOffice.Models
@model DoctorOffice.Models.Patient

<div class="patientSearch">
  <h2><strong>Search a Patient</strong></h2>

  <div id="patientSearchForm">
    <h4>Enter your search criteria below:</h4>
    @using (Html.BeginForm())
    {
      @Html.Label("By Last Name")
      <p><strong>
      @Html.TextBoxFor((model => model.LastName), new { @class="form-control"})
      </p>

      @Html.Label("By DOB")
      <p><strong>
      @Html.TextBoxFor((model => model.DOB), new { @type ="date", @class="form-control"})
      </p>
      
      <input class="w3-button w3-indigo" type="submit" value="Search" style="cursor: pointer">
    }
  </div>

</div>

DoctorOffice.Solution/DoctorOffice/Views/Patients/SearchResult.cshtml
@{
  Layout = "_Layout";
  ViewBag.Title = "Search Results Patients";
}

@using DoctorOffice.Models;
@model List<DoctorOffice.Models.Patient>

<div class="patientSearchResult">
  <h2><strong>Search Results of Patients</strong></h2>

  <div id="patientSearchLists">
    @if (Model.Count == 0)
    {
      <h3>No patients have been found</h3>
    }
    @foreach (Patient patient in Model)
    {
      <h3>@Html.ActionLink($"{patient.LastName}", "Details", new {id = patient.PatientId})</h3>
    }
  </div>
  <div class="exceptionError">
    @if (TempData.ContainsKey("ErrorMessage"))
    {
    <h4 class="exceptionError">@TempData["ErrorMessage"]</h4>
    }
  </div>

</div>